# Cleaning

## Table of Contents
- [Data Imports](#Data-Imports)
- [Manual Classification](#Manual-Classification)
    - [Iowa Data](#Iowa-Data)
    - [Texas Data](#Texas-Data)
    - [Wisconsin Data](#Wisconsin-Data)
- [Data Cleaning](#Data-Cleaning)

In [102]:
import pandas as pd
import datetime as dt

from warnings import catch_warnings
from warnings import filterwarnings
import warnings

warnings.simplefilter(action="ignore")

## Data Imports

In [322]:
df_WI = pd.read_csv('../datasets/df_WI.csv')
df_WI.head()

,Unnamed: 0,Date,Favorites,Geolocation,HashTags,Mentions,Retweets,Text,User,target,user_split,user_text,location
0,0,2019-07-19 22:40:31+00:00,0,NaN,#Respect,@BBCWorld @BigCatRescue,1,Nice to have a positive story about big cats for a change! #Respect India floods: Tired tiger takes nap in resident's bed via @BBCWorld https://www.bbc.com/news/world-asia-india-49041722 @BigCatRescue,Gabriettaa,0,Gabriettaa,Gabriettaa Nice to have a positive story about big cats for a change! #Respect India floods: Tired tiger takes nap in resident's bed via @BBCWorld https://www.bbc.com/news/world-asia-india-49041722 @BigCatRescue,WI
1,1,2019-07-19 22:26:34+00:00,0,NaN,NaN,NaN,0,my dad just told me to flood my car so I can get a new one.. alright bet,chaaasiti04,1,chaaasiti04,chaaasiti04 my dad just told me to flood my car so I can get a new one.. alright bet,WI
2,2,2019-07-19 22:19:05+00:00,1,NaN,NaN,NaN,2,"Happy B-day Reggie, from the office!!!",JDenius,1,JDenius,"JDenius Happy B-day Reggie, from the office!!!",WI
3,3,2019-07-19 22:17:13+00:00,0,NaN,NaN,NaN,0,Something about how crime will magically drop if we plant a few things in vacant lots,beganovic2021,1,beganovic2021,beganovic2021 Something about how crime will magically drop if we plant a few things in vacant lots,WI
4,4,2019-07-19 20:57:18+00:00,0,NaN,NaN,NaN,0,Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true,RiskItAllRichy,1,RiskItAllRichy,RiskItAllRichy Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true,WI

In [323]:
df_TX = pd.read_csv('../datasets/df_TX.csv')
df_TX.head()

,Unnamed: 0,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,0,LisaAbeyta,"Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",2016-06-23 23:59:36+00:00,0,0,NaN,#nmwx #nm,NaN,LisaAbeyta,"LisaAbeyta Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",1,TX
1,1,iembot_rlx,"At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",2016-06-23 23:53:45+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",1,TX
2,2,iembot_rlx,"At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",2016-06-23 23:50:46+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",1,TX
3,3,iembot_rlx,"At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",2016-06-23 23:48:01+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",1,TX
4,4,iembot_rlx,"At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",2016-06-23 22:27:16+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",1,TX

In [324]:
df_IA = pd.read_csv('../datasets/df_IA.csv')
df_IA.head()

,Unnamed: 0,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,0,TooCute504,Took the time out to volunteer in BR today. People are still recovering from the flood. Help is… https://www.instagram.com/p/BLFA-gEjZXO/,2016-10-02 23:06:20+00:00,0,0,NaN,NaN,NaN,TooCute504,TooCute504 Took the time out to volunteer in BR today. People are still recovering from the flood. Help is… https://www.instagram.com/p/BLFA-gEjZXO/,0,IA
1,1,juliakate,The great Paducah Flood Wall Murals... this Atomic City/Quilt City… https://www.instagram.com/p/BLE-XocA4B1Ufpk0NzoxQyNMR3Bam9_vAdcWO00/,2016-10-02 22:43:33+00:00,0,0,NaN,NaN,NaN,juliakate,juliakate The great Paducah Flood Wall Murals... this Atomic City/Quilt City… https://www.instagram.com/p/BLE-XocA4B1Ufpk0NzoxQyNMR3Bam9_vAdcWO00/,0,IA
2,2,Slapfish_2009,The Barman's Fund and USBG Tailgate Benefit for Flood Relief is on now #DrinkWithPurpose https://www.swarmapp.com/c/7iq4SxJtU4B,2016-10-02 20:32:22+00:00,0,0,NaN,#DrinkWithPurpose,NaN,Slapfish 2009,Slapfish 2009 The Barman's Fund and USBG Tailgate Benefit for Flood Relief is on now #DrinkWithPurpose https://www.swarmapp.com/c/7iq4SxJtU4B,0,IA
3,3,AhleahZoe1,Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,2016-10-02 18:01:34+00:00,0,0,NaN,NaN,NaN,AhleahZoe1,AhleahZoe1 Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,1,IA
4,4,katyxbeth,Last night sure was rainy as seen right before the flood gates opened up but I had a lot of fun!… https://www.instagram.com/p/BLEdPahhizf/,2016-10-02 17:54:06+00:00,0,0,NaN,NaN,NaN,katyxbeth,katyxbeth Last night sure was rainy as seen right before the flood gates opened up but I had a lot of fun!… https://www.instagram.com/p/BLEdPahhizf/,0,IA

## Manual Classification

### Iowa Data

Splitting the Iowa data into seperate y=1 and y=0 dfs.

In [325]:
df_IA_1 = df_IA[df_IA['target']==1]
df_IA_0 = df_IA[df_IA['target']==0]

Starting with y=1 target in the Iowa df:

In [326]:
df_IA_1.head()

,Unnamed: 0,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
3,3,AhleahZoe1,Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,2016-10-02 18:01:34+00:00,0,0,NaN,NaN,NaN,AhleahZoe1,AhleahZoe1 Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,1,IA
6,6,amyh2671,"#youarewelcomehere Holy Spirit! Come, flood this place with joy, abundantlife, and… https://www.instagram.com/p/BLEJd-EDGYj/",2016-10-02 15:01:18+00:00,0,0,NaN,#youarewelcomehere,NaN,amyh2671,"amyh2671 #youarewelcomehere Holy Spirit! Come, flood this place with joy, abundantlife, and… https://www.instagram.com/p/BLEJd-EDGYj/",1,IA
7,7,WeatherByBrian,"Minneapolis, MN: It's official now! Flood Warning for Hennepin, MN until Mon, Oct 03 at 13:00:00 CDT. https://alerts.weather.gov/cap/wwacapget.php?x=MN1256195EFA5C.FloodWarning.1256196ECFE0MN.MPXFLSMPX.1fed262b8d7a637c8f96871ebba62e8d",2016-10-02 14:36:14+00:00,0,0,NaN,NaN,NaN,WeatherByBrian,"WeatherByBrian Minneapolis, MN: It's official now! Flood Warning for Hennepin, MN until Mon, Oct 03 at 13:00:00 CDT. https://alerts.weather.gov/cap/wwacapget.php?x=MN1256195EFA5C.FloodWarning.1256196ECFE0MN.MPXFLSMPX.1fed262b8d7a637c8f96871ebba62e8d",1,IA
8,8,NWSDodgeCity,Move to higher ground! Flash Flood Warning including Sun City KS until 2:45 PM CDT,2016-10-02 13:52:17+00:00,0,1,NaN,NaN,NaN,NWSDodgeCity,NWSDodgeCity Move to higher ground! Flash Flood Warning including Sun City KS until 2:45 PM CDT,1,IA
9,9,TotalTrafficMCO,"Flash floods, caution in #Orange on Pne Hills Rd Both NB/SB at Hwy 50 #traffic http://bit.ly/ZE5wVb",2016-10-02 06:12:37+00:00,0,0,NaN,#Orange #traffic,NaN,TotalTrafficMCO,"TotalTrafficMCO Flash floods, caution in #Orange on Pne Hills Rd Both NB/SB at Hwy 50 #traffic http://bit.ly/ZE5wVb",1,IA

Creating a y=0 column as a 'check' in the y=1 df.

In [327]:
df_IA_1['check'] = 0

Inspecting individual user tweeting frequencies as starting point for analysis.

In [328]:
df_IA_1['user_split'].value_counts().head()

iembot arx         60
NWSRaleigh         41
iembot rah         40
iembot dmx         32
USGS TexasFlood    29
Name: user_split, dtype: int64

Through inspection and our domain knowlegde, we see that users with 'NWS', 'iembot', 'NWS', or 'CP' in their username appear to be associated with y=1, so we can change the value of the check for these from 0 to 1.

In [329]:
df_IA_1['check'][df_IA_1[df_IA_1['user_split'].str.contains('NWS')].index] = 1
df_IA_1['check'][df_IA_1[df_IA_1['user_split'].str.contains('iembot')].index] = 1
df_IA_1['check'][df_IA_1[df_IA_1['user_split'].str.contains('USGS')].index] = 1
df_IA_1['check'][df_IA_1[df_IA_1['user_split'].str.contains('CP')].index] = 1

In [330]:
df_IA_1['check'].value_counts(normalize=True)

1    0.733835
0    0.266165
Name: check, dtype: float64

*Note that approximately 75% of our y=1 data is from users with 'NWS', 'iembot', 'NWS', or 'CP' in their names.*

Based on domain knowlege, we compiled a list of specific strings associated with true y=1 targets. Note that our list is case sensitive to ensure.

In [331]:
flood_1 = ['flood warning', 'intersection', 'flood waters', 'flood (warning)', 'traffic',
          'edu', 'flash']

In [332]:
for word in flood_1:
    for i in df_IA_1.index:
        col = df_IA_1['Text'][i].lower()
        if col.find(word)>-1:
            df_IA_1['check'][i]=1

In [333]:
df_IA_1['check'].value_counts()

1    523
0    142
Name: check, dtype: int64

Manual Inspection:  
We will identify any true y=1.

In [334]:
df_IA_1[df_IA_1['check']==0].index

Int64Index([  6,  11,  12,  28,  29,  31,  32,  33,  34,  38,
            ...
            658, 659, 664, 666, 667, 668, 669, 670, 671, 672],
           dtype='int64', length=142)

In [335]:
df_IA_1[df_IA_1['check']==0]['Text'][55]

KeyError: 55

In [336]:
ind_1 = [41,42,55, 84,86, 87, 121, 122, 144, 150, 151, 216, 217, 220, 221, 
         224, 225, 286, 303, 467, 485, 543, 589, 606, 618, 620,629]
df_IA_1['check'][ind_1]=1

In [337]:
df_IA_1['check'].value_counts(normalize=True)

1    0.810526
0    0.189474
Name: check, dtype: float64

Initially 18.9% of our y=1 targets were false positives. We will fix this by reassigning these targets to y=0, and dropping the 'check' column.

In [338]:
df_IA_1['target'] = df_IA_1['check']
df_IA_1.drop(columns = ['check'], inplace = True)

Inspecting initial y=0 case, IA df:

Note: Since GetOldTweets scraper is not very precise with respect to state boundaries and we know from the FEMA dataset that there wasn't a severe flood in Iowa in the scraped time period, I will remove any tweets referring to an actual flood outside of Iowa.

In [339]:
df_IA_0.head()

,Unnamed: 0,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,0,TooCute504,Took the time out to volunteer in BR today. People are still recovering from the flood. Help is… https://www.instagram.com/p/BLFA-gEjZXO/,2016-10-02 23:06:20+00:00,0,0,NaN,NaN,NaN,TooCute504,TooCute504 Took the time out to volunteer in BR today. People are still recovering from the flood. Help is… https://www.instagram.com/p/BLFA-gEjZXO/,0,IA
1,1,juliakate,The great Paducah Flood Wall Murals... this Atomic City/Quilt City… https://www.instagram.com/p/BLE-XocA4B1Ufpk0NzoxQyNMR3Bam9_vAdcWO00/,2016-10-02 22:43:33+00:00,0,0,NaN,NaN,NaN,juliakate,juliakate The great Paducah Flood Wall Murals... this Atomic City/Quilt City… https://www.instagram.com/p/BLE-XocA4B1Ufpk0NzoxQyNMR3Bam9_vAdcWO00/,0,IA
2,2,Slapfish_2009,The Barman's Fund and USBG Tailgate Benefit for Flood Relief is on now #DrinkWithPurpose https://www.swarmapp.com/c/7iq4SxJtU4B,2016-10-02 20:32:22+00:00,0,0,NaN,#DrinkWithPurpose,NaN,Slapfish 2009,Slapfish 2009 The Barman's Fund and USBG Tailgate Benefit for Flood Relief is on now #DrinkWithPurpose https://www.swarmapp.com/c/7iq4SxJtU4B,0,IA
4,4,katyxbeth,Last night sure was rainy as seen right before the flood gates opened up but I had a lot of fun!… https://www.instagram.com/p/BLEdPahhizf/,2016-10-02 17:54:06+00:00,0,0,NaN,NaN,NaN,katyxbeth,katyxbeth Last night sure was rainy as seen right before the flood gates opened up but I had a lot of fun!… https://www.instagram.com/p/BLEdPahhizf/,0,IA
5,5,ShandrikaJ_Love,It's Baxter the Love Alive Dog!!!!!! Rescued from the flood after 7 weeks of being out there!!!!… https://www.instagram.com/p/BLEZIztgGMH/,2016-10-02 17:18:13+00:00,0,0,NaN,NaN,NaN,ShandrikaJ Love,ShandrikaJ Love It's Baxter the Love Alive Dog!!!!!! Rescued from the flood after 7 weeks of being out there!!!!… https://www.instagram.com/p/BLEZIztgGMH/,0,IA

Our top users have the same attributes that we previously determined were indicative of a flood: 'iembot,' 'NWS,' and 'USGS.' Through manual inspection, we see that these do warn of actual floods; however, they warn of floods outside of Iowa, and therfore, we will remove these rows from the dataframe, as we are assuming that in a production we will have specific geolocation data.

In [340]:
df_IA_0.drop(index = df_IA_0[df_IA_0['user_split'].str.contains('iembot')].index, inplace = True)
df_IA_0.drop(index = df_IA_0[df_IA_0['user_split'].str.contains('USGS')].index, inplace = True)
df_IA_0.drop(index = df_IA_0[df_IA_0['user_split'].str.contains('NSW')].index, inplace = True)
df_IA_0.drop(index = df_IA_0[df_IA_0['user_split'].str.contains('CP')].index, inplace = True)

Creating and exporting an 'adjusted' Iowa dataframe.

In [341]:
df_IA_adjusted = pd.concat([df_IA_1, df_IA_0], ignore_index = True)
df_IA_adjusted.head()

,Unnamed: 0,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,3,AhleahZoe1,Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,2016-10-02 18:01:34+00:00,0,0,NaN,NaN,NaN,AhleahZoe1,AhleahZoe1 Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,1,IA
1,6,amyh2671,"#youarewelcomehere Holy Spirit! Come, flood this place with joy, abundantlife, and… https://www.instagram.com/p/BLEJd-EDGYj/",2016-10-02 15:01:18+00:00,0,0,NaN,#youarewelcomehere,NaN,amyh2671,"amyh2671 #youarewelcomehere Holy Spirit! Come, flood this place with joy, abundantlife, and… https://www.instagram.com/p/BLEJd-EDGYj/",0,IA
2,7,WeatherByBrian,"Minneapolis, MN: It's official now! Flood Warning for Hennepin, MN until Mon, Oct 03 at 13:00:00 CDT. https://alerts.weather.gov/cap/wwacapget.php?x=MN1256195EFA5C.FloodWarning.1256196ECFE0MN.MPXFLSMPX.1fed262b8d7a637c8f96871ebba62e8d",2016-10-02 14:36:14+00:00,0,0,NaN,NaN,NaN,WeatherByBrian,"WeatherByBrian Minneapolis, MN: It's official now! Flood Warning for Hennepin, MN until Mon, Oct 03 at 13:00:00 CDT. https://alerts.weather.gov/cap/wwacapget.php?x=MN1256195EFA5C.FloodWarning.1256196ECFE0MN.MPXFLSMPX.1fed262b8d7a637c8f96871ebba62e8d",1,IA
3,8,NWSDodgeCity,Move to higher ground! Flash Flood Warning including Sun City KS until 2:45 PM CDT,2016-10-02 13:52:17+00:00,0,1,NaN,NaN,NaN,NWSDodgeCity,NWSDodgeCity Move to higher ground! Flash Flood Warning including Sun City KS until 2:45 PM CDT,1,IA
4,9,TotalTrafficMCO,"Flash floods, caution in #Orange on Pne Hills Rd Both NB/SB at Hwy 50 #traffic http://bit.ly/ZE5wVb",2016-10-02 06:12:37+00:00,0,0,NaN,#Orange #traffic,NaN,TotalTrafficMCO,"TotalTrafficMCO Flash floods, caution in #Orange on Pne Hills Rd Both NB/SB at Hwy 50 #traffic http://bit.ly/ZE5wVb",1,IA

In [342]:
# df_IA_adjusted.to_csv('../datasets/df_adjusted_IA.csv')

In [343]:
df_IA_adjusted = pd.read_csv('../datasets/df_adjusted_IA.csv')
df_IA_adjusted.head()

,Unnamed: 0,Unnamed: 0.1,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,0,3,AhleahZoe1,Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,2016-10-02 18:01:34+00:00,0,0,NaN,NaN,NaN,AhleahZoe1,AhleahZoe1 Flood waters. @Downtown Burlington IA https://www.instagram.com/p/BLEeGU6j09N/,1,IA
1,1,6,amyh2671,"#youarewelcomehere Holy Spirit! Come, flood this place with joy, abundantlife, and… https://www.instagram.com/p/BLEJd-EDGYj/",2016-10-02 15:01:18+00:00,0,0,NaN,#youarewelcomehere,NaN,amyh2671,"amyh2671 #youarewelcomehere Holy Spirit! Come, flood this place with joy, abundantlife, and… https://www.instagram.com/p/BLEJd-EDGYj/",0,IA
2,2,7,WeatherByBrian,"Minneapolis, MN: It's official now! Flood Warning for Hennepin, MN until Mon, Oct 03 at 13:00:00 CDT. https://alerts.weather.gov/cap/wwacapget.php?x=MN1256195EFA5C.FloodWarning.1256196ECFE0MN.MPXFLSMPX.1fed262b8d7a637c8f96871ebba62e8d",2016-10-02 14:36:14+00:00,0,0,NaN,NaN,NaN,WeatherByBrian,"WeatherByBrian Minneapolis, MN: It's official now! Flood Warning for Hennepin, MN until Mon, Oct 03 at 13:00:00 CDT. https://alerts.weather.gov/cap/wwacapget.php?x=MN1256195EFA5C.FloodWarning.1256196ECFE0MN.MPXFLSMPX.1fed262b8d7a637c8f96871ebba62e8d",1,IA
3,3,8,NWSDodgeCity,Move to higher ground! Flash Flood Warning including Sun City KS until 2:45 PM CDT,2016-10-02 13:52:17+00:00,0,1,NaN,NaN,NaN,NWSDodgeCity,NWSDodgeCity Move to higher ground! Flash Flood Warning including Sun City KS until 2:45 PM CDT,1,IA
4,4,9,TotalTrafficMCO,"Flash floods, caution in #Orange on Pne Hills Rd Both NB/SB at Hwy 50 #traffic http://bit.ly/ZE5wVb",2016-10-02 06:12:37+00:00,0,0,NaN,#Orange #traffic,NaN,TotalTrafficMCO,"TotalTrafficMCO Flash floods, caution in #Orange on Pne Hills Rd Both NB/SB at Hwy 50 #traffic http://bit.ly/ZE5wVb",1,IA

### Texas Data

In [344]:
df_TX.head()

,Unnamed: 0,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,0,LisaAbeyta,"Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",2016-06-23 23:59:36+00:00,0,0,NaN,#nmwx #nm,NaN,LisaAbeyta,"LisaAbeyta Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",1,TX
1,1,iembot_rlx,"At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",2016-06-23 23:53:45+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",1,TX
2,2,iembot_rlx,"At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",2016-06-23 23:50:46+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",1,TX
3,3,iembot_rlx,"At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",2016-06-23 23:48:01+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",1,TX
4,4,iembot_rlx,"At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",2016-06-23 22:27:16+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",1,TX

Splitting the Iowa data into seperate y=1 and y=0 dfs.

In [345]:
df_TX_1 = df_TX[df_TX['target']==1]
df_TX_0 = df_TX[df_TX['target']==0]

In [346]:
pd.set_option('display.max_rows', 1000)
pd.set_option('max_colwidth', 500)

df_TX_1:

In [347]:
df_TX_1;

Through inspection, compiled list called list_of_index containing false positives in the target y=1 df. Changing the targets of these to 0. We will also drop any non-english tweets.

In [348]:
list_of_index = [6, 46, 13, 16, 30, 57, 58, 59, 74, 85, 87, 88, 89, 90, 94, 95, 96, 100, 105, 108, 124, 127, 
                 135, 139, 141, 154, 155, 157, 158, 161, 162, 163, 166, 167, 
                 169, 171, 172, 173, 174, 175,  178, 179, 
                 180, 181, 183, 184, 190, 216, 227, 243, 244, 252, 257, 259, 291, 288, 293, 298, 
                 310, 309, 311, 313, 323, 325, 334, 336, 358, 
                 361, 360, 371, 366, 386, 411, 416, 417, 418, 419, 425, 426, 427, 428, 441, 442, 443, 449, 455, 459, 460, 461, 
                 462, 463, 646, 647, 648, 649, 654, 656, 671, 677, 
                 475, 512, 549, 577, 578, 579, 581, 582, 589, 590, 596, 597,  
                 480, 535, 547, 583, 592, 606,  629, 631, 
                 656, 658, 663, 665, 672, 673, 678,  683, 694, 681, 682, 695, 703, 704, 712, 721, 730, 731, 732, 733, 802,
                 729, 753, 834, 854, 859, 860, 952, 997, 999]

In [349]:
for num in list_of_index:
    df_TX_1['target'][num] = 0

In [350]:
df_TX_1['target'].value_counts()

1    852
0    148
Name: target, dtype: int64

In [351]:
df_TX_1.drop(index = [294, 727], inplace=True)

df_TX_0:

In [352]:
df_TX_0.drop(index = df_TX_0[df_TX_0['user_split'].str.contains('iembot')].index, inplace = True)
df_TX_0.drop(index = df_TX_0[df_TX_0['user_split'].str.contains('NWS')].index, inplace = True)
df_TX_0.drop(index = df_TX_0[df_TX_0['user_split'].str.contains('USGS')].index, inplace = True)
df_TX_0.drop(index = df_TX_0[df_TX_0['user_split'].str.contains('CP')].index, inplace = True)

In [353]:
df_TX_adjusted = pd.concat([df_TX_1, df_TX_0], ignore_index = True)
df_TX_adjusted.head()

,Unnamed: 0,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,0,LisaAbeyta,"Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",2016-06-23 23:59:36+00:00,0,0,NaN,#nmwx #nm,NaN,LisaAbeyta,"LisaAbeyta Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",1,TX
1,1,iembot_rlx,"At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",2016-06-23 23:53:45+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",1,TX
2,2,iembot_rlx,"At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",2016-06-23 23:50:46+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",1,TX
3,3,iembot_rlx,"At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",2016-06-23 23:48:01+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",1,TX
4,4,iembot_rlx,"At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",2016-06-23 22:27:16+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",1,TX

In [354]:
#df_TX_adjusted.to_csv('../datasets/df_adjusted_TX.csv')

In [355]:
df_TX_adjusted = pd.read_csv('../datasets/df_adjusted_TX.csv')
df_TX_adjusted.head()

,Unnamed: 0,Unnamed: 0.1,User,Text,Date,Favorites,Retweets,Mentions,HashTags,Geolocation,user_split,user_text,target,location
0,0,0,LisaAbeyta,"Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",2016-06-23 23:59:36+00:00,0,0,NaN,#nmwx #nm,NaN,LisaAbeyta,"LisaAbeyta Flash flood warning until 7 PM #nmwx #nm @Albuquerque, New Mexico https://www.instagram.com/p/BHBCyLQB-jK/",1,TX
1,1,1,iembot_rlx,"At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",2016-06-23 23:53:45+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:51 PM, 2 NNE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232351/201606232351",1,TX
2,2,2,iembot_rlx,"At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",2016-06-23 23:50:46+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:48 PM, 4 SSE Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232348/201606232348",1,TX
3,3,3,iembot_rlx,"At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",2016-06-23 23:48:01+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 7:44 PM, Rush [Boyd Co, KY] EMERGENCY MNGR reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232344/201606232344",1,TX
4,4,4,iembot_rlx,"At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",2016-06-23 22:27:16+00:00,0,0,NaN,#RLX,NaN,iembot rlx,"iembot rlx At 6:03 PM, 3 SW Amma [Roane Co, WV] DEPT OF HIGHWAYS reports FLASH FLOOD #RLX http://mesonet.agron.iastate.edu/lsr/#RLX/201606232203/201606232203",1,TX

### Wisconsin Data

In [356]:
df_WI.head()

,Unnamed: 0,Date,Favorites,Geolocation,HashTags,Mentions,Retweets,Text,User,target,user_split,user_text,location
0,0,2019-07-19 22:40:31+00:00,0,NaN,#Respect,@BBCWorld @BigCatRescue,1,Nice to have a positive story about big cats for a change! #Respect India floods: Tired tiger takes nap in resident's bed via @BBCWorld https://www.bbc.com/news/world-asia-india-49041722 @BigCatRescue,Gabriettaa,0,Gabriettaa,Gabriettaa Nice to have a positive story about big cats for a change! #Respect India floods: Tired tiger takes nap in resident's bed via @BBCWorld https://www.bbc.com/news/world-asia-india-49041722 @BigCatRescue,WI
1,1,2019-07-19 22:26:34+00:00,0,NaN,NaN,NaN,0,my dad just told me to flood my car so I can get a new one.. alright bet,chaaasiti04,1,chaaasiti04,chaaasiti04 my dad just told me to flood my car so I can get a new one.. alright bet,WI
2,2,2019-07-19 22:19:05+00:00,1,NaN,NaN,NaN,2,"Happy B-day Reggie, from the office!!!",JDenius,1,JDenius,"JDenius Happy B-day Reggie, from the office!!!",WI
3,3,2019-07-19 22:17:13+00:00,0,NaN,NaN,NaN,0,Something about how crime will magically drop if we plant a few things in vacant lots,beganovic2021,1,beganovic2021,beganovic2021 Something about how crime will magically drop if we plant a few things in vacant lots,WI
4,4,2019-07-19 20:57:18+00:00,0,NaN,NaN,NaN,0,Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true,RiskItAllRichy,1,RiskItAllRichy,RiskItAllRichy Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true,WI

In [357]:
df_WI_1 = df_WI[df_WI['target']==1]
df_WI_0 = df_WI[df_WI['target']==0]

In [358]:
df_WI_1;

In [359]:
 # drop null row so can search over column
df_WI_1.drop(index=df_WI_1[df_WI_1['Text'].isnull()].index, inplace = True)

In [360]:
df_WI_1[df_WI_1['Text'].str.contains('Biscuit')].index

Int64Index([121, 122, 123, 124, 125, 126, 127, 129, 131, 132, 133, 134, 135,
            136, 137, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 151,
            152],
           dtype='int64')

In [361]:
df_WI_1['target'].value_counts(ascending=False)

1    344
Name: target, dtype: int64

In [363]:
df_WI_1[df_WI_1['target']==1];

In [364]:
list_of_index = [1, 2, 3, 4, 6, 8, 9, 10, 11, 14, 15, 18, 25, 26, 27, 29, 30,31, 34, 37,
                40, 41, 43, 48, 49,50, 51, 52, 56, 60, 63, 64, 66, 72, 74, 76, 81, 83, 86, 88, 91,
                 121, 122, 123, 124, 125, 126, 127, 129, 131, 132, 133, 134, 135,
            136, 137, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 151, 152,
                92, 98, 99, 108, 109, 110, 112, 113, 115, 116, 118, 155, 156, 160, 163, 165, 166, 168, 
                 169,170, 172, 173, 174, 176, 178, 180, 181, 190,192, 198, 199, 200, 203, 205, 206, 208,
                 211, 213, 214, 217, 218, 219, 220, 221, 222, 223, 225, 226, 227, 228, 229, 230, 231,
                232, 233, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 247,
                248, 253, 255, 263, 266, 268, 275, 278, 280, 281, 286, 
                 302, 304, 308, 326, 345, 352
                ]

In [365]:
len(list_of_index)

152

In [366]:
for num in list_of_index:
    df_WI_1['target'][num] = 0

In [367]:
df_WI_1.drop(index = [13, 164], inplace = True)

initial y=0 for WI df

In [368]:
df_WI_0.drop(index = df_WI_0[df_WI_0['user_split'].str.contains('iembot')].index, inplace = True)
df_WI_0.drop(index = df_WI_0[df_WI_0['user_split'].str.contains('NWS')].index, inplace = True)

In [371]:
df_WI_adjusted = pd.concat([df_WI_1, df_WI_0], ignore_index = True)
df_WI_adjusted.head()

,Unnamed: 0,Date,Favorites,Geolocation,HashTags,Mentions,Retweets,Text,User,target,user_split,user_text,location
0,1,2019-07-19 22:26:34+00:00,0,NaN,NaN,NaN,0,my dad just told me to flood my car so I can get a new one.. alright bet,chaaasiti04,0,chaaasiti04,chaaasiti04 my dad just told me to flood my car so I can get a new one.. alright bet,WI
1,2,2019-07-19 22:19:05+00:00,1,NaN,NaN,NaN,2,"Happy B-day Reggie, from the office!!!",JDenius,0,JDenius,"JDenius Happy B-day Reggie, from the office!!!",WI
2,3,2019-07-19 22:17:13+00:00,0,NaN,NaN,NaN,0,Something about how crime will magically drop if we plant a few things in vacant lots,beganovic2021,0,beganovic2021,beganovic2021 Something about how crime will magically drop if we plant a few things in vacant lots,WI
3,4,2019-07-19 20:57:18+00:00,0,NaN,NaN,NaN,0,Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true,RiskItAllRichy,0,RiskItAllRichy,RiskItAllRichy Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true,WI
4,5,2019-07-19 19:53:44+00:00,0,NaN,NaN,@RAGBRAI_IOWA,2,Riding the bus along I29 to @RAGBRAI_IOWA and seeing the lingering flood waters. Devastating,CajunCy,1,CajunCy,CajunCy Riding the bus along I29 to @RAGBRAI_IOWA and seeing the lingering flood waters. Devastating,WI

In [372]:
df_WI_adjusted.to_csv('df_adjusted_WI.csv')

In [374]:
df_WI_adjusted = pd.read_csv('df_adjusted_WI.csv')
df_WI_adjusted.shape

(671, 14)

## Data Cleaning

##### Combining the dataframes

In [375]:
df_concat = pd.concat([df_WI_adjusted, df_TX_adjusted, df_IA_adjusted], ignore_index = True)

In [376]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3039 entries, 0 to 3038
Data columns (total 14 columns):
Date            3039 non-null object
Favorites       3039 non-null int64
Geolocation     0 non-null float64
HashTags        1462 non-null object
Mentions        223 non-null object
Retweets        3039 non-null int64
Text            3039 non-null object
Unnamed: 0      3039 non-null int64
Unnamed: 0.1    3039 non-null int64
User            3039 non-null object
location        3039 non-null object
target          3039 non-null int64
user_split      3039 non-null object
user_text       3039 non-null object
dtypes: float64(1), int64(5), object(8)
memory usage: 332.5+ KB

In [377]:
# drop Unanamed: 0, Unnameed: 0.1, geolocation, User
df_concat.drop(columns = ['Unnamed: 0', 'Unnamed: 0.1', 'Geolocation', 'User'], inplace = True)

In [378]:
# Change Date column to datetime
df_concat['Date'] = pd.to_datetime(df_concat['Date'])

In [379]:
df_concat['Date'].dtypes

datetime64[ns, UTC]

In [380]:
# Analyze Nulls
df_concat.isnull().sum().sort_values(ascending=False)

Mentions      2816
HashTags      1577
user_text        0
user_split       0
target           0
location         0
Text             0
Retweets         0
Favorites        0
Date             0
dtype: int64

In [381]:
df_concat['Mentions'].fillna('None', inplace = True)
df_concat['HashTags'].fillna('None', inplace = True)

In [382]:
df_concat.shape

(3039, 10)

In [383]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3039 entries, 0 to 3038
Data columns (total 10 columns):
Date          3039 non-null datetime64[ns, UTC]
Favorites     3039 non-null int64
HashTags      3039 non-null object
Mentions      3039 non-null object
Retweets      3039 non-null int64
Text          3039 non-null object
location      3039 non-null object
target        3039 non-null int64
user_split    3039 non-null object
user_text     3039 non-null object
dtypes: datetime64[ns, UTC](1), int64(3), object(6)
memory usage: 237.5+ KB

In [384]:
#df_concat.to_csv('../datasets/df_IA_TX_WI_clean_adjusted.csv')

In [386]:
pd.read_csv('../datasets/df_IA_TX_WI_clean_adjusted.csv').head()

,Unnamed: 0,Date,Favorites,HashTags,Mentions,Retweets,Text,location,target,user_split,user_text
0,0,2019-07-19 22:26:34+00:00,0,None,None,0,my dad just told me to flood my car so I can get a new one.. alright bet,WI,0,chaaasiti04,chaaasiti04 my dad just told me to flood my car so I can get a new one.. alright bet
1,1,2019-07-19 22:19:05+00:00,1,None,None,2,"Happy B-day Reggie, from the office!!!",WI,0,JDenius,"JDenius Happy B-day Reggie, from the office!!!"
2,2,2019-07-19 22:17:13+00:00,0,None,None,0,Something about how crime will magically drop if we plant a few things in vacant lots,WI,0,beganovic2021,beganovic2021 Something about how crime will magically drop if we plant a few things in vacant lots
3,3,2019-07-19 20:57:18+00:00,0,None,None,0,Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true,WI,0,RiskItAllRichy,RiskItAllRichy Lol mine too. I’ve been avoiding floods for the simple fact ima be addicted to going and I’m at that age to embrace it lol sad but true
4,4,2019-07-19 19:53:44+00:00,0,None,@RAGBRAI_IOWA,2,Riding the bus along I29 to @RAGBRAI_IOWA and seeing the lingering flood waters. Devastating,WI,1,CajunCy,CajunCy Riding the bus along I29 to @RAGBRAI_IOWA and seeing the lingering flood waters. Devastating